---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  scss-lint:
    enabled: true
  fixme:
    enabled: true
ratings:
   paths:
   - "**.js"
exclude_paths:
- .node_modules/
